-- USERS
INSERT INTO users (uid, email) VALUES
('user1', 'alice@example.com'),
('user2', 'bob@test.org'),
('user3', 'charlie@mail.com'),
('user4', 'diana@test.org'),
('user5', 'ethan@mail.com'),
('user6', 'fiona@mail.com'),
('user7', 'george@test.org'),
('user8', 'hannah@mail.com'),
('user9', 'ian@mail.com'),
('user10', 'julia@test.org')
ON CONFLICT (uid) DO NOTHING;

-- BOOKS
INSERT INTO books (name, author, review, rating, cover, category, status, uid) VALUES
('Atomic Habits Vol 1', 'James Clear', 'A review of Atomic Habits Vol 1.', 4, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Science Fiction', 'Completed', 'user1'),
('Dune Vol 1', 'Frank Herbert', 'A review of Dune Vol 1.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Romance', 'Upcoming', 'user1'),
('Gone Girl Vol 1', 'Gillian Flynn', 'A review of Gone Girl Vol 1.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Others', 'Upcoming', 'user1'),
('Pride and Prejudice Vol 1', 'Jane Austen', 'A review of Pride and Prejudice Vol 1.', 3, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Self-Help', 'Reading', 'user1'),
('The Alchemist Vol 1', 'Paulo Coelho', 'A review of The Alchemist Vol 1.', 3, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Mystery', 'Completed', 'user1'),
('1984 Vol 1', 'George Orwell', 'A review of 1984 Vol 1.', 5, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Self-Help', 'Reading', 'user1'),
('To Kill a Mockingbird Vol 1', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 1.', 4, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Romance', 'Reading', 'user1'),
('The Great Gatsby Vol 1', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 1.', 4, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Mystery', 'Completed', 'user1'),
('The Power of Now Vol 1', 'Eckhart Tolle', 'A review of The Power of Now Vol 1.', 5, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Science Fiction', 'Reading', 'user1'),
('Thinking, Fast and Slow Vol 1', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 1.', 5, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Science Fiction', 'Upcoming', 'user1'),
('Atomic Habits Vol 2', 'James Clear', 'A review of Atomic Habits Vol 2.', 3, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Self-Help', 'Reading', 'user1'),
('Dune Vol 2', 'Frank Herbert', 'A review of Dune Vol 2.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Science Fiction', 'Upcoming', 'user1'),
('Gone Girl Vol 2', 'Gillian Flynn', 'A review of Gone Girl Vol 2.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Science Fiction', 'Completed', 'user1'),
('Pride and Prejudice Vol 2', 'Jane Austen', 'A review of Pride and Prejudice Vol 2.', 5, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Romance', 'Completed', 'user1'),
('The Alchemist Vol 2', 'Paulo Coelho', 'A review of The Alchemist Vol 2.', 5, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Mystery', 'Completed', 'user1'),
('1984 Vol 2', 'George Orwell', 'A review of 1984 Vol 2.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Science Fiction', 'Reading', 'user1'),
('To Kill a Mockingbird Vol 2', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 2.', 5, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Romance', 'Upcoming', 'user1'),
('The Great Gatsby Vol 2', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 2.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Science Fiction', 'Upcoming', 'user1'),
('The Power of Now Vol 2', 'Eckhart Tolle', 'A review of The Power of Now Vol 2.', 5, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Mystery', 'Upcoming', 'user1'),
('Thinking, Fast and Slow Vol 2', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 2.', 5, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Romance', 'Upcoming', 'user1'),
('Atomic Habits Vol 3', 'James Clear', 'A review of Atomic Habits Vol 3.', 5, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Science Fiction', 'Completed', 'user2'),
('Dune Vol 3', 'Frank Herbert', 'A review of Dune Vol 3.', 3, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Others', 'Upcoming', 'user2'),
('Gone Girl Vol 3', 'Gillian Flynn', 'A review of Gone Girl Vol 3.', 5, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Self-Help', 'Completed', 'user2'),
('Pride and Prejudice Vol 3', 'Jane Austen', 'A review of Pride and Prejudice Vol 3.', 5, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Mystery', 'Completed', 'user2'),
('The Alchemist Vol 3', 'Paulo Coelho', 'A review of The Alchemist Vol 3.', 3, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Self-Help', 'Reading', 'user2'),
('1984 Vol 3', 'George Orwell', 'A review of 1984 Vol 3.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Romance', 'Upcoming', 'user2'),
('To Kill a Mockingbird Vol 3', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 3.', 4, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Romance', 'Completed', 'user2'),
('The Great Gatsby Vol 3', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 3.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Mystery', 'Upcoming', 'user2'),
('The Power of Now Vol 3', 'Eckhart Tolle', 'A review of The Power of Now Vol 3.', 3, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Romance', 'Upcoming', 'user2'),
('Thinking, Fast and Slow Vol 3', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 3.', 5, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Romance', 'Upcoming', 'user2'),
('Atomic Habits Vol 4', 'James Clear', 'A review of Atomic Habits Vol 4.', 4, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Science Fiction', 'Reading', 'user2'),
('Dune Vol 4', 'Frank Herbert', 'A review of Dune Vol 4.', 4, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Self-Help', 'Reading', 'user2'),
('Gone Girl Vol 4', 'Gillian Flynn', 'A review of Gone Girl Vol 4.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Mystery', 'Upcoming', 'user2'),
('Pride and Prejudice Vol 4', 'Jane Austen', 'A review of Pride and Prejudice Vol 4.', 4, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Mystery', 'Reading', 'user2'),
('The Alchemist Vol 4', 'Paulo Coelho', 'A review of The Alchemist Vol 4.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Science Fiction', 'Completed', 'user2'),
('1984 Vol 4', 'George Orwell', 'A review of 1984 Vol 4.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Others', 'Upcoming', 'user2'),
('To Kill a Mockingbird Vol 4', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 4.', 5, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Self-Help', 'Upcoming', 'user2'),
('The Great Gatsby Vol 4', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 4.', 4, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Science Fiction', 'Completed', 'user2'),
('The Power of Now Vol 4', 'Eckhart Tolle', 'A review of The Power of Now Vol 4.', 5, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Romance', 'Upcoming', 'user2'),
('Thinking, Fast and Slow Vol 4', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 4.', 5, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Romance', 'Reading', 'user2'),
('Atomic Habits Vol 5', 'James Clear', 'A review of Atomic Habits Vol 5.', 3, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Self-Help', 'Upcoming', 'user3'),
('Dune Vol 5', 'Frank Herbert', 'A review of Dune Vol 5.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Romance', 'Upcoming', 'user3'),
('Gone Girl Vol 5', 'Gillian Flynn', 'A review of Gone Girl Vol 5.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Science Fiction', 'Reading', 'user3'),
('Pride and Prejudice Vol 5', 'Jane Austen', 'A review of Pride and Prejudice Vol 5.', 5, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Romance', 'Reading', 'user3'),
('The Alchemist Vol 5', 'Paulo Coelho', 'A review of The Alchemist Vol 5.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Science Fiction', 'Completed', 'user3'),
('1984 Vol 5', 'George Orwell', 'A review of 1984 Vol 5.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Self-Help', 'Completed', 'user3'),
('To Kill a Mockingbird Vol 5', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 5.', 4, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Romance', 'Reading', 'user3'),
('The Great Gatsby Vol 5', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 5.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Others', 'Reading', 'user3'),
('The Power of Now Vol 5', 'Eckhart Tolle', 'A review of The Power of Now Vol 5.', 3, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Others', 'Upcoming', 'user3'),
('Thinking, Fast and Slow Vol 5', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 5.', 3, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Science Fiction', 'Upcoming', 'user3');

INSERT INTO books (name, author, review, rating, cover, category, status, uid) VALUES
('Atomic Habits Vol 6', 'James Clear', 'A review of Atomic Habits Vol 6.', 5, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Others', 'Completed', 'user3'),
('Dune Vol 6', 'Frank Herbert', 'A review of Dune Vol 6.', 3, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Mystery', 'Upcoming', 'user3'),
('Gone Girl Vol 6', 'Gillian Flynn', 'A review of Gone Girl Vol 6.', 5, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Others', 'Completed', 'user3'),
('Pride and Prejudice Vol 6', 'Jane Austen', 'A review of Pride and Prejudice Vol 6.', 3, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Romance', 'Reading', 'user3'),
('The Alchemist Vol 6', 'Paulo Coelho', 'A review of The Alchemist Vol 6.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Romance', 'Completed', 'user3'),
('1984 Vol 6', 'George Orwell', 'A review of 1984 Vol 6.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Self-Help', 'Upcoming', 'user3'),
('To Kill a Mockingbird Vol 6', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 6.', 4, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Mystery', 'Upcoming', 'user3'),
('The Great Gatsby Vol 6', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 6.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Science Fiction', 'Completed', 'user3'),
('The Power of Now Vol 6', 'Eckhart Tolle', 'A review of The Power of Now Vol 6.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Mystery', 'Completed', 'user3'),
('Thinking, Fast and Slow Vol 6', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 6.', 5, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Science Fiction', 'Upcoming', 'user3'),
('Atomic Habits Vol 7', 'James Clear', 'A review of Atomic Habits Vol 7.', 3, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Science Fiction', 'Completed', 'user4'),
('Dune Vol 7', 'Frank Herbert', 'A review of Dune Vol 7.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Romance', 'Upcoming', 'user4'),
('Gone Girl Vol 7', 'Gillian Flynn', 'A review of Gone Girl Vol 7.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Romance', 'Upcoming', 'user4'),
('Pride and Prejudice Vol 7', 'Jane Austen', 'A review of Pride and Prejudice Vol 7.', 3, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Others', 'Completed', 'user4'),
('The Alchemist Vol 7', 'Paulo Coelho', 'A review of The Alchemist Vol 7.', 3, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Science Fiction', 'Reading', 'user4'),
('1984 Vol 7', 'George Orwell', 'A review of 1984 Vol 7.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Self-Help', 'Upcoming', 'user4'),
('To Kill a Mockingbird Vol 7', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 7.', 5, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Others', 'Upcoming', 'user4'),
('The Great Gatsby Vol 7', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 7.', 5, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Self-Help', 'Upcoming', 'user4'),
('The Power of Now Vol 7', 'Eckhart Tolle', 'A review of The Power of Now Vol 7.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Romance', 'Upcoming', 'user4'),
('Thinking, Fast and Slow Vol 7', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 7.', 4, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Self-Help', 'Completed', 'user4'),
('Atomic Habits Vol 8', 'James Clear', 'A review of Atomic Habits Vol 8.', 4, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Others', 'Completed', 'user4'),
('Dune Vol 8', 'Frank Herbert', 'A review of Dune Vol 8.', 4, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Self-Help', 'Reading', 'user4'),
('Gone Girl Vol 8', 'Gillian Flynn', 'A review of Gone Girl Vol 8.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Others', 'Reading', 'user4'),
('Pride and Prejudice Vol 8', 'Jane Austen', 'A review of Pride and Prejudice Vol 8.', 5, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Others', 'Reading', 'user4'),
('The Alchemist Vol 8', 'Paulo Coelho', 'A review of The Alchemist Vol 8.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Others', 'Completed', 'user4'),
('1984 Vol 8', 'George Orwell', 'A review of 1984 Vol 8.', 4, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Romance', 'Reading', 'user4'),
('To Kill a Mockingbird Vol 8', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 8.', 3, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Romance', 'Completed', 'user4'),
('The Great Gatsby Vol 8', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 8.', 5, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Self-Help', 'Completed', 'user4'),
('The Power of Now Vol 8', 'Eckhart Tolle', 'A review of The Power of Now Vol 8.', 3, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Science Fiction', 'Reading', 'user4'),
('Thinking, Fast and Slow Vol 8', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 8.', 4, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Romance', 'Completed', 'user4'),
('Atomic Habits Vol 9', 'James Clear', 'A review of Atomic Habits Vol 9.', 4, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Mystery', 'Reading', 'user5'),
('Dune Vol 9', 'Frank Herbert', 'A review of Dune Vol 9.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Science Fiction', 'Completed', 'user5'),
('Gone Girl Vol 9', 'Gillian Flynn', 'A review of Gone Girl Vol 9.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Romance', 'Upcoming', 'user5'),
('Pride and Prejudice Vol 9', 'Jane Austen', 'A review of Pride and Prejudice Vol 9.', 4, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Self-Help', 'Upcoming', 'user5'),
('The Alchemist Vol 9', 'Paulo Coelho', 'A review of The Alchemist Vol 9.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Science Fiction', 'Reading', 'user5'),
('1984 Vol 9', 'George Orwell', 'A review of 1984 Vol 9.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Mystery', 'Reading', 'user5'),
('To Kill a Mockingbird Vol 9', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 9.', 3, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Others', 'Completed', 'user5'),
('The Great Gatsby Vol 9', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 9.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Romance', 'Reading', 'user5'),
('The Power of Now Vol 9', 'Eckhart Tolle', 'A review of The Power of Now Vol 9.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Mystery', 'Upcoming', 'user5'),
('Thinking, Fast and Slow Vol 9', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 9.', 4, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Mystery', 'Completed', 'user5'),
('Atomic Habits Vol 10', 'James Clear', 'A review of Atomic Habits Vol 10.', 5, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Others', 'Reading', 'user5'),
('Dune Vol 10', 'Frank Herbert', 'A review of Dune Vol 10.', 3, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Others', 'Completed', 'user5'),
('Gone Girl Vol 10', 'Gillian Flynn', 'A review of Gone Girl Vol 10.', 4, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Self-Help', 'Completed', 'user5'),
('Pride and Prejudice Vol 10', 'Jane Austen', 'A review of Pride and Prejudice Vol 10.', 5, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Science Fiction', 'Upcoming', 'user5'),
('The Alchemist Vol 10', 'Paulo Coelho', 'A review of The Alchemist Vol 10.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Others', 'Completed', 'user5'),
('1984 Vol 10', 'George Orwell', 'A review of 1984 Vol 10.', 4, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Science Fiction', 'Reading', 'user5'),
('To Kill a Mockingbird Vol 10', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 10.', 3, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Mystery', 'Upcoming', 'user5'),
('The Great Gatsby Vol 10', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 10.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Romance', 'Reading', 'user5'),
('The Power of Now Vol 10', 'Eckhart Tolle', 'A review of The Power of Now Vol 10.', 5, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Science Fiction', 'Completed', 'user5'),
('Thinking, Fast and Slow Vol 10', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 10.', 4, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Others', 'Reading', 'user5');

INSERT INTO books (name, author, review, rating, cover, category, status, uid) VALUES
('Atomic Habits Vol 11', 'James Clear', 'A review of Atomic Habits Vol 11.', 4, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Romance', 'Upcoming', 'user6'),
('Dune Vol 11', 'Frank Herbert', 'A review of Dune Vol 11.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Science Fiction', 'Reading', 'user6'),
('Gone Girl Vol 11', 'Gillian Flynn', 'A review of Gone Girl Vol 11.', 4, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Science Fiction', 'Reading', 'user6'),
('Pride and Prejudice Vol 11', 'Jane Austen', 'A review of Pride and Prejudice Vol 11.', 4, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Romance', 'Reading', 'user6'),
('The Alchemist Vol 11', 'Paulo Coelho', 'A review of The Alchemist Vol 11.', 3, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Romance', 'Completed', 'user6'),
('1984 Vol 11', 'George Orwell', 'A review of 1984 Vol 11.', 5, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Others', 'Completed', 'user6'),
('To Kill a Mockingbird Vol 11', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 11.', 4, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Romance', 'Completed', 'user6'),
('The Great Gatsby Vol 11', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 11.', 4, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Science Fiction', 'Reading', 'user6'),
('The Power of Now Vol 11', 'Eckhart Tolle', 'A review of The Power of Now Vol 11.', 3, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Mystery', 'Completed', 'user6'),
('Thinking, Fast and Slow Vol 11', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 11.', 3, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Science Fiction', 'Completed', 'user6'),
('Atomic Habits Vol 12', 'James Clear', 'A review of Atomic Habits Vol 12.', 3, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Science Fiction', 'Upcoming', 'user6'),
('Dune Vol 12', 'Frank Herbert', 'A review of Dune Vol 12.', 4, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Others', 'Upcoming', 'user6'),
('Gone Girl Vol 12', 'Gillian Flynn', 'A review of Gone Girl Vol 12.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Science Fiction', 'Completed', 'user6'),
('Pride and Prejudice Vol 12', 'Jane Austen', 'A review of Pride and Prejudice Vol 12.', 3, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Self-Help', 'Reading', 'user6'),
('The Alchemist Vol 12', 'Paulo Coelho', 'A review of The Alchemist Vol 12.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Romance', 'Completed', 'user6'),
('1984 Vol 12', 'George Orwell', 'A review of 1984 Vol 12.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Science Fiction', 'Reading', 'user6'),
('To Kill a Mockingbird Vol 12', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 12.', 3, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Mystery', 'Reading', 'user6'),
('The Great Gatsby Vol 12', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 12.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Self-Help', 'Completed', 'user6'),
('The Power of Now Vol 12', 'Eckhart Tolle', 'A review of The Power of Now Vol 12.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Romance', 'Upcoming', 'user6'),
('Thinking, Fast and Slow Vol 12', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 12.', 4, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Others', 'Reading', 'user6'),
('Atomic Habits Vol 13', 'James Clear', 'A review of Atomic Habits Vol 13.', 3, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Science Fiction', 'Reading', 'user7'),
('Dune Vol 13', 'Frank Herbert', 'A review of Dune Vol 13.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Self-Help', 'Upcoming', 'user7'),
('Gone Girl Vol 13', 'Gillian Flynn', 'A review of Gone Girl Vol 13.', 4, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Science Fiction', 'Completed', 'user7'),
('Pride and Prejudice Vol 13', 'Jane Austen', 'A review of Pride and Prejudice Vol 13.', 3, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Others', 'Upcoming', 'user7'),
('The Alchemist Vol 13', 'Paulo Coelho', 'A review of The Alchemist Vol 13.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Self-Help', 'Reading', 'user7'),
('1984 Vol 13', 'George Orwell', 'A review of 1984 Vol 13.', 5, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Self-Help', 'Completed', 'user7'),
('To Kill a Mockingbird Vol 13', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 13.', 4, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Romance', 'Completed', 'user7'),
('The Great Gatsby Vol 13', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 13.', 5, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Science Fiction', 'Completed', 'user7'),
('The Power of Now Vol 13', 'Eckhart Tolle', 'A review of The Power of Now Vol 13.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Others', 'Reading', 'user7'),
('Thinking, Fast and Slow Vol 13', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 13.', 5, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Science Fiction', 'Completed', 'user7'),
('Atomic Habits Vol 14', 'James Clear', 'A review of Atomic Habits Vol 14.', 5, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Romance', 'Upcoming', 'user7'),
('Dune Vol 14', 'Frank Herbert', 'A review of Dune Vol 14.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Self-Help', 'Reading', 'user7'),
('Gone Girl Vol 14', 'Gillian Flynn', 'A review of Gone Girl Vol 14.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Mystery', 'Upcoming', 'user7'),
('Pride and Prejudice Vol 14', 'Jane Austen', 'A review of Pride and Prejudice Vol 14.', 5, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Others', 'Upcoming', 'user7'),
('The Alchemist Vol 14', 'Paulo Coelho', 'A review of The Alchemist Vol 14.', 3, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Science Fiction', 'Upcoming', 'user7'),
('1984 Vol 14', 'George Orwell', 'A review of 1984 Vol 14.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Romance', 'Reading', 'user7'),
('To Kill a Mockingbird Vol 14', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 14.', 3, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Romance', 'Reading', 'user7'),
('The Great Gatsby Vol 14', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 14.', 5, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Others', 'Upcoming', 'user7'),
('The Power of Now Vol 14', 'Eckhart Tolle', 'A review of The Power of Now Vol 14.', 3, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Self-Help', 'Upcoming', 'user7'),
('Thinking, Fast and Slow Vol 14', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 14.', 5, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Self-Help', 'Reading', 'user7'),
('Atomic Habits Vol 15', 'James Clear', 'A review of Atomic Habits Vol 15.', 4, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Others', 'Upcoming', 'user8'),
('Dune Vol 15', 'Frank Herbert', 'A review of Dune Vol 15.', 4, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Mystery', 'Completed', 'user8'),
('Gone Girl Vol 15', 'Gillian Flynn', 'A review of Gone Girl Vol 15.', 4, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Self-Help', 'Reading', 'user8'),
('Pride and Prejudice Vol 15', 'Jane Austen', 'A review of Pride and Prejudice Vol 15.', 5, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Others', 'Reading', 'user8'),
('The Alchemist Vol 15', 'Paulo Coelho', 'A review of The Alchemist Vol 15.', 5, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Self-Help', 'Upcoming', 'user8'),
('1984 Vol 15', 'George Orwell', 'A review of 1984 Vol 15.', 5, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Others', 'Reading', 'user8'),
('To Kill a Mockingbird Vol 15', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 15.', 3, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Others', 'Completed', 'user8'),
('The Great Gatsby Vol 15', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 15.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Mystery', 'Reading', 'user8'),
('The Power of Now Vol 15', 'Eckhart Tolle', 'A review of The Power of Now Vol 15.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Mystery', 'Completed', 'user8'),
('Thinking, Fast and Slow Vol 15', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 15.', 3, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Mystery', 'Reading', 'user8');

INSERT INTO books (name, author, review, rating, cover, category, status, uid) VALUES
('Atomic Habits Vol 16', 'James Clear', 'A review of Atomic Habits Vol 16.', 5, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Romance', 'Upcoming', 'user8'),
('Dune Vol 16', 'Frank Herbert', 'A review of Dune Vol 16.', 4, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Science Fiction', 'Upcoming', 'user8'),
('Gone Girl Vol 16', 'Gillian Flynn', 'A review of Gone Girl Vol 16.', 4, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Self-Help', 'Completed', 'user8'),
('Pride and Prejudice Vol 16', 'Jane Austen', 'A review of Pride and Prejudice Vol 16.', 4, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Mystery', 'Completed', 'user8'),
('The Alchemist Vol 16', 'Paulo Coelho', 'A review of The Alchemist Vol 16.', 3, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Mystery', 'Completed', 'user8'),
('1984 Vol 16', 'George Orwell', 'A review of 1984 Vol 16.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Science Fiction', 'Upcoming', 'user8'),
('To Kill a Mockingbird Vol 16', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 16.', 5, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Science Fiction', 'Upcoming', 'user8'),
('The Great Gatsby Vol 16', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 16.', 4, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Others', 'Upcoming', 'user8'),
('The Power of Now Vol 16', 'Eckhart Tolle', 'A review of The Power of Now Vol 16.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Science Fiction', 'Completed', 'user8'),
('Thinking, Fast and Slow Vol 16', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 16.', 4, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Mystery', 'Reading', 'user8'),
('Atomic Habits Vol 17', 'James Clear', 'A review of Atomic Habits Vol 17.', 4, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Mystery', 'Reading', 'user9'),
('Dune Vol 17', 'Frank Herbert', 'A review of Dune Vol 17.', 3, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Science Fiction', 'Upcoming', 'user9'),
('Gone Girl Vol 17', 'Gillian Flynn', 'A review of Gone Girl Vol 17.', 4, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Science Fiction', 'Upcoming', 'user9'),
('Pride and Prejudice Vol 17', 'Jane Austen', 'A review of Pride and Prejudice Vol 17.', 4, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Science Fiction', 'Reading', 'user9'),
('The Alchemist Vol 17', 'Paulo Coelho', 'A review of The Alchemist Vol 17.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Romance', 'Completed', 'user9'),
('1984 Vol 17', 'George Orwell', 'A review of 1984 Vol 17.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Others', 'Upcoming', 'user9'),
('To Kill a Mockingbird Vol 17', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 17.', 3, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Others', 'Reading', 'user9'),
('The Great Gatsby Vol 17', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 17.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Romance', 'Upcoming', 'user9'),
('The Power of Now Vol 17', 'Eckhart Tolle', 'A review of The Power of Now Vol 17.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Science Fiction', 'Reading', 'user9'),
('Thinking, Fast and Slow Vol 17', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 17.', 4, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Self-Help', 'Completed', 'user9'),
('Atomic Habits Vol 18', 'James Clear', 'A review of Atomic Habits Vol 18.', 4, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Science Fiction', 'Reading', 'user9'),
('Dune Vol 18', 'Frank Herbert', 'A review of Dune Vol 18.', 5, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Mystery', 'Reading', 'user9'),
('Gone Girl Vol 18', 'Gillian Flynn', 'A review of Gone Girl Vol 18.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Mystery', 'Upcoming', 'user9'),
('Pride and Prejudice Vol 18', 'Jane Austen', 'A review of Pride and Prejudice Vol 18.', 3, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Self-Help', 'Upcoming', 'user9'),
('The Alchemist Vol 18', 'Paulo Coelho', 'A review of The Alchemist Vol 18.', 3, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Romance', 'Upcoming', 'user9'),
('1984 Vol 18', 'George Orwell', 'A review of 1984 Vol 18.', 5, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Self-Help', 'Reading', 'user9'),
('To Kill a Mockingbird Vol 18', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 18.', 4, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Mystery', 'Completed', 'user9'),
('The Great Gatsby Vol 18', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 18.', 5, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Romance', 'Upcoming', 'user9'),
('The Power of Now Vol 18', 'Eckhart Tolle', 'A review of The Power of Now Vol 18.', 4, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Others', 'Completed', 'user9'),
('Thinking, Fast and Slow Vol 18', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 18.', 3, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Self-Help', 'Completed', 'user9'),
('Atomic Habits Vol 19', 'James Clear', 'A review of Atomic Habits Vol 19.', 5, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Mystery', 'Upcoming', 'user10'),
('Dune Vol 19', 'Frank Herbert', 'A review of Dune Vol 19.', 3, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Mystery', 'Reading', 'user10'),
('Gone Girl Vol 19', 'Gillian Flynn', 'A review of Gone Girl Vol 19.', 5, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Others', 'Reading', 'user10'),
('Pride and Prejudice Vol 19', 'Jane Austen', 'A review of Pride and Prejudice Vol 19.', 3, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Science Fiction', 'Upcoming', 'user10'),
('The Alchemist Vol 19', 'Paulo Coelho', 'A review of The Alchemist Vol 19.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Romance', 'Upcoming', 'user10'),
('1984 Vol 19', 'George Orwell', 'A review of 1984 Vol 19.', 3, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Romance', 'Upcoming', 'user10'),
('To Kill a Mockingbird Vol 19', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 19.', 4, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Others', 'Reading', 'user10'),
('The Great Gatsby Vol 19', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 19.', 3, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Self-Help', 'Reading', 'user10'),
('The Power of Now Vol 19', 'Eckhart Tolle', 'A review of The Power of Now Vol 19.', 5, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Others', 'Reading', 'user10'),
('Thinking, Fast and Slow Vol 19', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 19.', 4, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Others', 'Upcoming', 'user10'),
('Atomic Habits Vol 20', 'James Clear', 'A review of Atomic Habits Vol 20.', 3, 'https://covers.openlibrary.org/b/isbn/0735211299-M.jpg', 'Romance', 'Upcoming', 'user10'),
('Dune Vol 20', 'Frank Herbert', 'A review of Dune Vol 20.', 4, 'https://covers.openlibrary.org/b/isbn/0441172717-M.jpg', 'Mystery', 'Completed', 'user10'),
('Gone Girl Vol 20', 'Gillian Flynn', 'A review of Gone Girl Vol 20.', 3, 'https://covers.openlibrary.org/b/isbn/0307588378-M.jpg', 'Mystery', 'Completed', 'user10'),
('Pride and Prejudice Vol 20', 'Jane Austen', 'A review of Pride and Prejudice Vol 20.', 4, 'https://covers.openlibrary.org/b/isbn/0141439513-M.jpg', 'Science Fiction', 'Completed', 'user10'),
('The Alchemist Vol 20', 'Paulo Coelho', 'A review of The Alchemist Vol 20.', 4, 'https://covers.openlibrary.org/b/isbn/0061122416-M.jpg', 'Romance', 'Reading', 'user10'),
('1984 Vol 20', 'George Orwell', 'A review of 1984 Vol 20.', 5, 'https://covers.openlibrary.org/b/isbn/0451524934-M.jpg', 'Romance', 'Reading', 'user10'),
('To Kill a Mockingbird Vol 20', 'Harper Lee', 'A review of To Kill a Mockingbird Vol 20.', 3, 'https://covers.openlibrary.org/b/isbn/0446310786-M.jpg', 'Mystery', 'Reading', 'user10'),
('The Great Gatsby Vol 20', 'F. Scott Fitzgerald', 'A review of The Great Gatsby Vol 20.', 4, 'https://covers.openlibrary.org/b/isbn/0743273567-M.jpg', 'Self-Help', 'Upcoming', 'user10'),
('The Power of Now Vol 20', 'Eckhart Tolle', 'A review of The Power of Now Vol 20.', 5, 'https://covers.openlibrary.org/b/isbn/1577314808-M.jpg', 'Science Fiction', 'Reading', 'user10'),
('Thinking, Fast and Slow Vol 20', 'Daniel Kahneman', 'A review of Thinking, Fast and Slow Vol 20.', 3, 'https://covers.openlibrary.org/b/isbn/0374533555-M.jpg', 'Others', 'Reading', 'user10');
