name: keepalive

on:
  schedule:
    - cron: "2-52/10 * * * *"   # every 10 min; stagger per repo (e.g., add 2, 4, 6 min offsets)
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      URLS_CSV: ${{ secrets.KEEPALIVE_URLS }}   # set per repo
      UA: "KeepAliveBot/1.0 (+github-actions)"
    steps:
      - name: Ping endpoints
        shell: bash
        run: |
          if [ -z "$URLS_CSV" ]; then
            echo "No KEEPALIVE_URLS secret set; nothing to ping."
            exit 0
          fi

          IFS=',' read -ra URLS <<< "$URLS_CSV"

          ping_url () {
            local url="$1"
            echo "::group::Pinging $url"
            curl -fLsS \
              --max-time 15 \
              --retry 3 \
              --retry-delay 2 \
              -H "Cache-Control: no-cache" \
              -H "Pragma: no-cache" \
              -H "User-Agent: $UA" \
              "$url" >/dev/null || echo "WARN: failed $url"
            echo "::endgroup::"
          }

          sleep $((RANDOM % 10))  # tiny jitter

          for u in "${URLS[@]}"; do
            u="$(echo "$u" | xargs)"   # trim
            [ -n "$u" ] && ping_url "$u"
          done


